version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -port 9000 -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "9000:9000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID="key"
      - AWS_SECRET_ACCESS_KEY="secret"
      - AWS_SESSION_TOKEN="session"
      - AWS_DEFAULT_REGION=us-east-1